Traceback (most recent call last):
  File "/w/halld-scshelf2101/lng/Mambaforge/envs/PyAmpTools/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/w/halld-scshelf2101/lng/Mambaforge/envs/PyAmpTools/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/w/halld-scshelf2101/lng/Mambaforge/envs/PyAmpTools/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/w/halld-scshelf2101/lng/Mambaforge/envs/PyAmpTools/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/w/halld-scshelf2101/lng/Mambaforge/envs/PyAmpTools/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/w/halld-scshelf2101/lng/Mambaforge/envs/PyAmpTools/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/w/halld-scshelf2101/lng/Mambaforge/envs/PyAmpTools/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
nll = runFits(ati, N=numRnd, USE_MPI=USE_MPI)
------------------

----- stdout -----
LIKELIHOOD BEFORE MINIMIZATION: 112356.11732090596
----- stdout -----
Resetting source kin in /w/halld-scshelf2101/lng/WORK/PyAmpTools/tests/samples/SIMPLE_EXAMPLE/samples/data_generated_samples.root
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[8], line 1[0m
[0;32m----> 1[0m nll [38;5;241m=[39m [43mrunFits[49m[43m([49m[43mati[49m[43m,[49m[43m [49m[43mN[49m[38;5;241;43m=[39;49m[43mnumRnd[49m[43m,[49m[43m [49m[43mUSE_MPI[49m[38;5;241;43m=[39;49m[43mUSE_MPI[49m[43m)[49m

File [0;32m/w/halld-scshelf2101/lng/Mambaforge/envs/PyAmpTools/lib/python3.9/site-packages/fit.py:47[0m, in [0;36mrunFits[0;34m(ati, N, RANK_MPI, maxIter, USE_MPI, seedfile, useMinos, hesse)[0m
[1;32m     44[0m fitManager[38;5;241m.[39msetMaxIterations(maxIter)
[1;32m     46[0m [38;5;28;01mif[39;00m N [38;5;241m==[39m [38;5;241m0[39m: [38;5;66;03m# No randomization[39;00m
[0;32m---> 47[0m     bFitFailed, minNLL [38;5;241m=[39m [43mperformFit[49m( ati, [38;5;124m'[39m[38;5;124m0[39m[38;5;124m'[39m, [38;5;241m*[39mfitargs )
[1;32m     48[0m     [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m'[39m[38;5;124mLIKELIHOOD AFTER MINIMIZATION (NO RANDOMIZATION): [39m[38;5;132;01m{[39;00mminNLL[38;5;132;01m}[39;00m[38;5;124m'[39m)
[1;32m     50[0m [38;5;28;01melse[39;00m: [38;5;66;03m# Randomized parameters[39;00m

[0;31mNameError[0m: name 'performFit' is not defined

