Traceback (most recent call last):
  File "/w/halld-scshelf2101/lng/micromamba/envs/pyamptools2/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/w/halld-scshelf2101/lng/micromamba/envs/pyamptools2/lib/python3.9/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/w/halld-scshelf2101/lng/micromamba/envs/pyamptools2/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/w/halld-scshelf2101/lng/micromamba/envs/pyamptools2/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/w/halld-scshelf2101/lng/micromamba/envs/pyamptools2/lib/python3.9/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/w/halld-scshelf2101/lng/micromamba/envs/pyamptools2/lib/python3.9/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/w/halld-scshelf2101/lng/micromamba/envs/pyamptools2/lib/python3.9/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
show_pdf("RESULTS/PLOTS/gen_curves.pdf")
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
File [0;32m/w/halld-scshelf2101/lng/micromamba/envs/pyamptools2/lib/python3.9/site-packages/pdf2image/pdf2image.py:602[0m, in [0;36mpdfinfo_from_path[0;34m(pdf_path, userpw, ownerpw, poppler_path, rawdates, timeout, first_page, last_page)[0m
[1;32m    601[0m [38;5;28;01mif[39;00m [38;5;124m"[39m[38;5;124mPages[39m[38;5;124m"[39m [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m d:
[0;32m--> 602[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m
[1;32m    604[0m [38;5;28;01mreturn[39;00m d

[0;31mValueError[0m: 

During handling of the above exception, another exception occurred:

[0;31mPDFPageCountError[0m                         Traceback (most recent call last)
Cell [0;32mIn[5], line 1[0m
[0;32m----> 1[0m [43mshow_pdf[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mRESULTS/PLOTS/gen_curves.pdf[39;49m[38;5;124;43m"[39;49m[43m)[49m

Cell [0;32mIn[1], line 23[0m, in [0;36mshow_pdf[0;34m(pdf_path, dpi)[0m
[1;32m     18[0m [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21mshow_pdf[39m(pdf_path, dpi[38;5;241m=[39m[38;5;241m150[39m):
[1;32m     19[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[1;32m     20[0m [38;5;124;03m    Show a PDF in the notebook cell, rasterized since vscode jupyter cannot render PDFs[39;00m
[1;32m     21[0m [38;5;124;03m    [39;00m
[1;32m     22[0m [38;5;124;03m    """[39;00m
[0;32m---> 23[0m     img [38;5;241m=[39m [43mconvert_from_path[49m[43m([49m[43mpdf_path[49m[43m,[49m[43m [49m[43mdpi[49m[38;5;241;43m=[39;49m[43mdpi[49m[43m)[49m[[38;5;241m0[39m]
[1;32m     24[0m     display(img)

File [0;32m/w/halld-scshelf2101/lng/micromamba/envs/pyamptools2/lib/python3.9/site-packages/pdf2image/pdf2image.py:127[0m, in [0;36mconvert_from_path[0;34m(pdf_path, dpi, output_folder, first_page, last_page, fmt, jpegopt, thread_count, userpw, ownerpw, use_cropbox, strict, transparent, single_file, output_file, poppler_path, grayscale, size, paths_only, use_pdftocairo, timeout, hide_annotations)[0m
[1;32m    124[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(poppler_path, PurePath):
[1;32m    125[0m     poppler_path [38;5;241m=[39m poppler_path[38;5;241m.[39mas_posix()
[0;32m--> 127[0m page_count [38;5;241m=[39m [43mpdfinfo_from_path[49m[43m([49m
[1;32m    128[0m [43m    [49m[43mpdf_path[49m[43m,[49m[43m [49m[43muserpw[49m[43m,[49m[43m [49m[43mownerpw[49m[43m,[49m[43m [49m[43mpoppler_path[49m[38;5;241;43m=[39;49m[43mpoppler_path[49m
[1;32m    129[0m [43m[49m[43m)[49m[[38;5;124m"[39m[38;5;124mPages[39m[38;5;124m"[39m]
[1;32m    131[0m [38;5;66;03m# We start by getting the output format, the buffer processing function and if we need pdftocairo[39;00m
[1;32m    132[0m parsed_fmt, final_extension, parse_buffer_func, use_pdfcairo_format [38;5;241m=[39m _parse_format(
[1;32m    133[0m     fmt, grayscale
[1;32m    134[0m )

File [0;32m/w/halld-scshelf2101/lng/micromamba/envs/pyamptools2/lib/python3.9/site-packages/pdf2image/pdf2image.py:611[0m, in [0;36mpdfinfo_from_path[0;34m(pdf_path, userpw, ownerpw, poppler_path, rawdates, timeout, first_page, last_page)[0m
[1;32m    607[0m     [38;5;28;01mraise[39;00m PDFInfoNotInstalledError(
[1;32m    608[0m         [38;5;124m"[39m[38;5;124mUnable to get page count. Is poppler installed and in PATH?[39m[38;5;124m"[39m
[1;32m    609[0m     )
[1;32m    610[0m [38;5;28;01mexcept[39;00m [38;5;167;01mValueError[39;00m:
[0;32m--> 611[0m     [38;5;28;01mraise[39;00m PDFPageCountError(
[1;32m    612[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mUnable to get page count.[39m[38;5;130;01m\n[39;00m[38;5;132;01m{[39;00merr[38;5;241m.[39mdecode([38;5;124m'[39m[38;5;124mutf8[39m[38;5;124m'[39m,[38;5;250m [39m[38;5;124m'[39m[38;5;124mignore[39m[38;5;124m'[39m)[38;5;132;01m}[39;00m[38;5;124m"[39m
[1;32m    613[0m     )

[0;31mPDFPageCountError[0m: Unable to get page count.
I/O Error: Couldn't open file 'RESULTS/PLOTS/gen_curves.pdf': No such file or directory.


